### ISSUE TITLE
configureUserIdUWP not implemented in GameAnalyticsExtern.cpp

### ISSUE THREAD

**Issue by MahdiGhiasi** [GameAnalytics/GA-SDK-CPP#101]
First, We've noticed that when calling ConfigureUserId on GameAnalytics Unity SDK, we get an exception:

    EntryPointNotFoundException: Unable to find an entry point named 'configureUserIdUWP' in 'GameAnalytics.UWP.dll'.

Upon further investigation, I've found that the Unity SDK internally calls a method from the native GA-SDK-CPP named `configureUserIdUWP`.

It seems that this method [is declared in GameAnalyticsExtern.h](https://github.com/GameAnalytics/GA-SDK-CPP/blob/master/source/gameanalytics/GameAnalyticsExtern.h#L100), but **there is no definition of it anywhere** within [GameAnalyticsExtern.cpp](https://github.com/GameAnalytics/GA-SDK-CPP/blob/master/source/gameanalytics/GameAnalyticsExtern.cpp) or [anywhere else in the repository](https://github.com/GameAnalytics/GA-SDK-CPP/search?q=configureUserIdUWP).

**Comment by the1schwartz** [comment]
Thanks for reporting this. This should be fixed in the latest version of the Unity SDK (v6.5.1)

**Comment by MahdiGhiasi** [comment]
Thanks for the quick update!
