### ISSUE TITLE
gameanalytics::GameAnalytics::configureWritablePath path limit 65 chars

### ISSUE THREAD

**Issue by irov** [GameAnalytics/GA-SDK-CPP#114]
`        std::array<char, 65> writablePath = {'\0'};
        snprintf(writablePath.data(), writablePath.size(), "%s", writablePath_ ? writablePath_ : "");
        `

please add platform dependens define this size like MAX_PATH (windows 260, unix base 1024)

thanks

**Comment by the1schwartz** [comment]
Thanks for reporting this. This should be fixed now
