### ISSUE TITLE
Nothing being reported.

### ISSUE THREAD

**Issue by arg0d** [GameAnalytics/GA-SDK-CPP#16]
I have added GameAnalytics to my builds. On Mac, it seemed to be reporting at least something. On Windows however, I don't get any events.

```
	GameAnalytics::configureUserId(userId);
	GameAnalytics::initialize("xxx", "xxx");	
	GameAnalytics::startSession();

	GameAnalytics::addErrorEvent(EGAErrorSeverity::Critical, "This is test error!");

```
I have compiled the SDK using:
python build/jenkins/build.py --target win32-vc140-static
I have added link dependencies listed on the main page of GitHub.

Could there be an issue of adding dependencies incorrectly, even though it compiles? GameAnalytics seems to be using MD, but I saw MT Boost dependencies. Could that be an issue?

My Debug build was using MD and the project compiled fine. My Release build was using MT and it was spewing link errors. I switched CRT to MD for Release build for now. The problem still remains that no events seem to be reported.

**Comment by arg0d** [comment]
Now I started seeing some kind of events out of nowhere.

```
	GameAnalytics::setEnabledInfoLog(true);
	GameAnalytics::setEnabledVerboseLog(true);

	GameAnalytics::configureBuild("0.0.0");
```

I added this just now, but the latest events in Live Feed are almost an hour old, so maybe GA is just under a heavy load? I guess that means everything is working fine!

My only concerns now are Boost MT dependencies.

**Comment by the1schwartz** [comment]
Glad it worked out for you, could very well be the system was heavy loaded but I don't know for sure. I'm not sure what your concern is regarding the Boost MT dependencies but you are more than welcome to submit a support ticket to support@gameanalytics.com and our support team will be happy to help you out with Amy problems or questions you might have.

**Comment by arg0d** [comment]
I have read in many places that MD and MT are not supposed to be mixed in libraries and .DDLs
Are these articles wrong, or am I missing something here?

**Comment by the1schwartz** [comment]
It is possible to build the boost libraries with /MD instead, the build scripts are located in GA-SDK-CPP\source\dependencies\boost\boost_1_60_0 folder for both 32-bit and 64-bit Windows. It requires to install b2 (follow this guide http://www.boost.org/doc/libs/1_60_0/doc/html/bbv2.html#bbv2.installation) before you run the scripts. Just edit the script and I believe you just need to add threading=single to arguments or else look here http://www.boost.org/build/doc/html/bbv2/overview/invocation.html for more options. We only use the Boost libraries for very simple things which are not shared outside its own boundaries. Hope this helps. Thanks again for using GameAnalytics.
