### ISSUE TITLE
Is it possible to use VC /MT version?

### ISSUE THREAD

**Issue by arg0d** [GameAnalytics/GA-SDK-CPP#20]
Hi,

The game I'm developing for Steam has no dependencies other than GA that required /MD option.

Adding VC2015 redist to dependencies on Steam seems to cause the installer to run every time, but that is probably a Steam issue, which I hope can be resolved when I contact someone from Steam tomorrow.

Another issue is that users can't even install VC2015 redist if they don't have a certain Windows update installed. This is a big problem for me and I need to figure this out fast.

I went to CMake generated VC project and changed to /MT option. I also had to add boost-mt-s 'filesystem' and 'system' binaries as dependencies for my project. I got them from an installer at:
https://sourceforge.net/projects/boost/files/boost-binaries/1.60.0/

Can you advise me if switching to /MT like that is a safe thing to do?

**Comment by the1schwartz** [comment]
In v1.3.0 we have actually removed the boost dependency so it is not needed anymore. All memory is contained within the library so there should be no problem using either /MD or /MT I think.

**Comment by arg0d** [comment]
I forgot to mention in last post, that I had to add -MSVCRT.lib for linking, because libcurl was complaining otherwise. 

I thought everything was fine, but it seems MSVCRT.lib is dynamic also, so my .exe still requires CRT installed on target computer.

Right now I'm trying to compile libcurl myself. There is a big list of targets available and I'm not sure which one to pick.
http://imgur.com/a/z5Rss

**Comment by the1schwartz** [comment]
It denpends if you want to create a static library (LIB) or shared library (DLL) for both libcurl and openssl.

**Comment by Subtixx** [comment]
Instead of wasted valuable company time on this, it would be better if GameAnalytics would provide libcurl & openssl already build with /MT. Also having a config for win32-vc120-mt-static/win64-vc120-mt-static since you already provide a win32-vc140-mt-static/win64-vc140-mt-static config option.
