### ISSUE TITLE
ERROR: Unsupported protocol ::::: FUNCTION: perform

### ISSUE THREAD

**Issue by mkdotcom** [GameAnalytics/GA-SDK-CPP#36]
Hello

I'm using GA-SDK-CPP on MacOsX
It doesn't work, I get this in the debug output:
 
[gameanalytics::logging::GALogger::sendNotificationMessage@272] Info/GameAnalytics: Event queue: Sending 5 events.
ERROR: Unsupported protocol ::::: FUNCTION: perform

Any idea what i am doing wrong?

Thanks a lot

**Comment by mkdotcom** [comment]
I just notice this message in GameAnalytics.cpp :

// TODO: Get HTTPS working on air for mac

**Comment by the1schwartz** [comment]
Yes I think I know what the issue is. The included curl library has not been built with https support. We are working to fix this. A fix should come very soon with the next update

**Comment by mkdotcom** [comment]
thanks! 👍

**Comment by the1schwartz** [comment]
This should now be fixed the latest version v1.3.7.

**Comment by mkdotcom** [comment]
great, thank you
