### ISSUE TITLE
Win32 build issue

### ISSUE THREAD

**Issue by mkdotcom** [GameAnalytics/GA-SDK-CPP#38]
Hello
On my computer using "build.bat" on Windows 10 with Visual Studio 2015 community installed leads to error when building win32 version.
Please see the log.txt attached file.

Thanks

[log.txt](https://github.com/GameAnalytics/GA-SDK-CPP/files/1242527/log.txt)

**Comment by the1schwartz** [comment]
We recently updated the script to support building with Visual Studio 2017 and the script by default tries to use Visual Studio 2017. We forgot to update the documentation regarding this but it is done now here: https://github.com/GameAnalytics/GA-SDK-CPP/wiki/Build. So to use Visual Studio 2015 call **build.bat -v 2015 [-t target]**

**Comment by mkdotcom** [comment]
thanks, it doesn't seems to work though. Using the "-v 2015" option display the help.

**Comment by the1schwartz** [comment]
Ah forgot merge develop branch into master branch. Try downloading the latest version on master branch now ;)

**Comment by mkdotcom** [comment]
perfect 👍 thanks !

**Comment by the1schwartz** [comment]
No problem, hope it is working for you now ;)

**Comment by mkdotcom** [comment]
it does, thanks you
