### ISSUE TITLE
Documentation mistakes

### ISSUE THREAD

**Issue by Subtixx** [GameAnalytics/GA-SDK-CPP#42]
In the documentation over on your website https://gameanalytics.com/docs/cpp-sdk it describes how to add certain allowed values. However the namespace has a mistake in it since it names the namespace as: `gameanalytics::cocos2d` which should just be `gameanalytics` also the documentation over there links to the documentation on github.

For example on section `Resource`:
> The resource type/currency to track. Has to be one of the [configured available resource currencies](https://github.com/GameAnalytics/GA-SDK-CPP/wiki/Configuration).
This string can only contain [A-Za-z] characters.

Oh and also it is not clear wether or not IAP, Gameplay are built-in or I still have to "allow" those.

**Comment by the1schwartz** [comment]
Hi. Thanks for the corrections for the docs, they have been fixed now. Regarding IAP you can send business events but there is no validation for them (we only do that for our native Android and iOS SDKs), so the business events will show up as non-validated in our web tool. Hope this answers your question regarding IAP or else free to contact our friendly support team here: http://gameanalytics.com/contact

**Comment by Subtixx** [comment]
Seems like the documentation in section Resource still points to Github. (If this isn't intentional..)

**Comment by the1schwartz** [comment]
No sorry I have just corrected that as well thanks.
