### ISSUE TITLE
Linking fails with Unreal Engine 4.18/4.19 on Linux because PIC is disabled

### ISSUE THREAD

**Issue by leyyin** [GameAnalytics/GA-SDK-CPP#51]
Hi, while trying to link my project against the plugin from https://github.com/GameAnalytics/GA-SDK-UNREAL with the precompiled library I got the following linking error:
```
Plugins/GameAnalytics/Source/ThirdParty/lib/linux/libGameAnalytics.a(GameAnalytics.cpp.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
```

I fixed this by compiling the library with `PIC` enabled. The fix commit can be found[ here](https://github.com/leyyin/GA-SDK-CPP/commit/1c3f33f86087c497f7a2634c806a7d29b5dcc784) (not sure if this breaks any other platforms).

I am running Ubuntu `16.04`.

Editor build with build type `Development`

**Comment by the1schwartz** [comment]
Thanks for the contribution. We will add in the next release.
