### ISSUE TITLE
crash on uwp

### ISSUE THREAD

**Issue by vincentely** [GameAnalytics/GA-SDK-CPP#59]
crashed sometimes on a c++ dx11 uwp game.  only add the GA initialize for data record.
here is the stack.

RaiseException
__ExceptionPtr::_RethrowException
__ExceptionPtrRethrow
Concurrency::details::_ExceptionHolder::_RethrowUserException
Concurrency::details::_Task_impl_base::_Wait
Concurrency::task_std::pair_enum gameanalytics::http::EGAHTTPApiResponse,Json::Value_ _::get
gameanalytics::state::GAState::startNewSession
gameanalytics::state::GAState::internalInitialize
std::range_error::~range_error
gameanalytics::threading::GAThreading::thread_routine

**Comment by the1schwartz** [comment]
This should be fixed in the latest version (v1.4.6)
