### ISSUE TITLE
Using const char* instead of const string& breaks linux UE plugin

### ISSUE THREAD

**Issue by leyyin** [GameAnalytics/GA-SDK-CPP#60]
The `const char*` strings gets corrupted, and I can see in `ga_log.txt` the strings the library gets are giberish.

GA-SDK-CPP Version: `1.4.5`
GA-SDK-UNREAL Version: `2.6.16`

This addition seems to be at fault:
https://github.com/GameAnalytics/GA-SDK-CPP/commit/3b7a7d0c1c72d318a192b0a2708a136279519f36#diff-ddc6f5b585eef97da41f60458f9782d0R23

Using `std::string&` seems to work fine though.

Why was this changed in 1.4.5?

**Comment by the1schwartz** [comment]
This issues should be fixed now. A release have been made for Unreal SDK (v2.6.17) and have been submitted to their marketplace as well, this has also been fixed in the C++ SDK for Linux.
