### ISSUE TITLE
"Ghost" background thread not shutting down after process exit.

### ISSUE THREAD

**Issue by ErickAlcan** [GameAnalytics/GA-SDK-CPP#75]
I'm importing the GA's static library (.lib) in a dynamic lib (.dll) which is loaded at runtime in the game process.

Just by including the GA lib in my project the game process won't shutdown properly after closing the game (which then calls kernel32::ExitProcess). Even if I don't call any GA function in my code and just ship the dll with GA's lib inside it the proccess won't shutdown correctly.

It's very weird **_why_** just by including the GA's lib in the dll this bug beggins. I have no clue whatsoever of **_why_** just by including the lib in the dll this problem rises up.

An odd remark is that if I call `gameanalytics::GameAnalytics::onQuit();` on `DLL_THREAD_DETACH` (inside my dll's `DllMain`) the process will shutdown properly. The problem with that approach is that the first time any thread finishes `DLL_THREAD_DETACH` will be called, so it is not a viable solution as I would have to keep starting the GA's system every time a thread is killed loosing track of user session among other problems. 

Does anyone have any clue about this problem? Any help would be very much appreaciated.

**Comment by ErickAlcan** [comment]
Anyone?

**Comment by the1schwartz** [comment]
Sorry for the late reply. I have been on holiday the whole of last week but I will have look into the issue now.

**Comment by the1schwartz** [comment]
Hi. This should be fixed in the lasted version (v.2.1.1). Let me know if you still experience this issue.
