### ISSUE TITLE
Win32 shared library blocking thread execution upon dll load

### ISSUE THREAD

**Issue by andresantacruz** [GameAnalytics/GA-SDK-CPP#79]
The .dll compiled using the project's build system to the target `win32-v141-shared` is blocking thread execution indefinitely upon a call to `LoadLibrary` or if loaded using the its import library.

It seems to be a deadlock but I don't have further information about it.

Any ideas about this problem?

**Comment by the1schwartz** [comment]
Ok thanks for reporting this. I will look into this.

**Comment by the1schwartz** [comment]
This should be fixed. The SDK uses on the windows some windows api calls for getting information about the device which causes the dll to freeze the application on loadlibrary so I had to disable these calls when building for dll. This is fixed in the latest version of the SDK (v2.1.2)
