### ISSUE TITLE
Can't disable debug log in GA-SDK-IOS 3.2.0

### ISSUE THREAD

**Issue by KAMIKAZEUA** [GameAnalytics/GA-SDK-CPP#80]
**I'm creating issue here, because here https://github.com/GameAnalytics/GA-SDK-IOS there is `NO` `issues` tab enabled.**

----------

I've set:

```
[GameAnalytics setEnabledInfoLog:false];
[GameAnalytics setEnabledVerboseLog:false];
```
But when my game has no access to internet every 5 sec or something I'm getting in log: 

`Warning/GA/Analytics: Event queue: Failed to send events to collector - Retrying next time`

This logs should be disabled. This is bug in iOS SDK.

**Comment by the1schwartz** [comment]
Warnings will always be shown, as these logs indicate the developer of something that he/she might need to take action on.

PS: You can always contact our friendly support team here https://gameanalytics.com/contact if you have feedback like these.

**Comment by KAMIKAZEUA** [comment]
It's shown TOO often, it's produces lagging on low devices. This should be once or I need to be able to disable this.

**Comment by KAMIKAZEUA** [comment]
Why you close this?
 Open that issues on Objc version of SDK and lets discuss there.

**Comment by the1schwartz** [comment]
Ok I will add a method to disable warnings logs for the next release.

**Comment by KAMIKAZEUA** [comment]
Thanks! So, after that issue can be closed here? Because if it's closed, can be lose from view :)

**Comment by the1schwartz** [comment]
Ok there is a new release out now (v3.2.1) with an added `setEnabledWarningLog` method
